apiVersion: v1
kind: Pod
metadata:
  name: todoapp-pod-1
  labels:
    app: todolist
spec:
  containers:
  - name: todoapp-container
    image: baga56789/todoapp:3.0.0
    ports:
    - containerPort: 8000
    env:
    - name: PYTHONUNBUFFERED
      value: "1"
    - name: DJANGO_SETTINGS_MODULE
      value: "todolist.settings"
---
apiVersion: v1
kind: Pod
metadata:
  name: todoapp-pod-2
  labels:
    app: todolist
spec:
  containers:
  - name: todoapp-container
    image: baga56789/todoapp:3.0.0
    ports:
    - containerPort: 8000
    env:
    - name: PYTHONUNBUFFERED
      value: "1"
    - name: DJANGO_SETTINGS_MODULE
      value: "todolist.settings"